
version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: cinema_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    

  backend:
    build: .
    env_file:
      - .env
    container_name: cinema_backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/cinemovies_db
      - POOL_MIN=2
      - POOL_MAX=10
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm run seed && npm run start"
volumes:
  mongo_data:
